Identificar las vocales en milisegundos [inicio/fin]

audacity

transformada de fourier


guardar el output del csv con un array de numpy con np.float32
sin headers




In [153]:
import scipy.io.wavfile
import numpy as np #aqui hi ha les estructures de dades que faig servir
import matplotlib.pyplot as plt #per dibuixar
from IPython.display import Audio #el reproductor d'audio
from numpy.fft import fft, ifft #podria fer numpy.fft en comptes de fer aquest

Fs, audio = scipy.io.wavfile.read('audio2.wav')
arr_data = np.genfromtxt('../datasets/vocales.csv', delimiter=',')
arr_labels = np.genfromtxt('../datasets/vocales.csv', delimiter=',', dtype=str)

Delete header and output

In [154]:
#elimino cabecera y output
arr_data = np.delete(arr_data, [0,-1], 0)
arr_data = np.delete(arr_data, [-1], 1)



In [155]:
def generate_vocals_frequencies(csv_data, audio, Fs):
  for i in range(len(csv_data)):
    start, end = csv_data[i]
    print(start, end)
    cut = audio[int(start*Fs):int(end*Fs)]
    print(cut)

    fourier = fft(cut)

    Fsmall = fourier[0:int(3000*len(cut)/Fs)] 

    filter = int(125*len(cut)/Fs)  #Tamaño estandar del filtro
    threeKHz = int(3000*len(cut)/Fs)
    to_process = np.sqrt((np.real(Fsmall)**2+np.imag(Fsmall)**2))

    out = np.zeros(len(to_process)-filter, dtype=np.float64)
    for i in range(len(to_process)-filter):
        for j in range(filter):
            out[i] += to_process[i+j]



    cut_filter = int(150 * len(cut) / Fs)
    max_points = []

    for i in range(3):
      curr_max_point = np.argmax(out) + filter
      max_points.append(curr_max_point)

      start_cut = curr_max_point-filter-cut_filter
      end_cut = curr_max_point + cut_filter - filter
      if (start_cut < 0):
        start_cut = 0
      
      out[start_cut:end_cut] = 0
    

    max_points.sort()


generate_vocals_frequencies(arr_data, audio, Fs)

7.819 8.027
[-5495 -5568 -5448 ... -1861 -1923 -1968]
[48, 183, 216]
13.311 13.416
[7553 7849 8201 ... 2421 2620 2781]
[31, 52, 91]
17.654 17.757
[2055 2097 2113 ...  396  386  354]
[21, 37, 57]
16.437 16.548
[-2189 -1769 -1369 ...  1686  1791  1817]
[18, 38, 68]
17.533 17.603
[ 389  440  496 ... 2919 2283 1562]
[15, 63, 94]
13.198 13.272
[   -5    -5    -5 ... -1725 -2027 -2379]
[16, 27, 71]
22.381 22.736
[-2772 -2961 -3057 ...   125   186   343]
[86, 156, 214]
29.798 29.917
[ 8523  8927  9241 ... -3503 -2923 -2358]
[73, 90, 111]
7.919 8.018
[-3003 -2774 -2576 ...  -395  -543  -687]
[24, 84, 141]
21.145 21.295
[ -872  -969 -1074 ... -2306 -2933 -3673]
[32, 61, 83]
12.718 12.862
[3982 4426 5087 ... -126 -109  -95]
[33, 71, 92]
20.144 20.337
[  37   60   81 ... -793 -750 -672]
[46, 92, 120]
6.305 6.419
[    5     4     4 ... -4125 -4707 -5598]
[26, 60, 250]
28.502 28.648
[ -38  -74 -110 ... -562 -524 -486]
[32, 53, 74]
51.107 51.185
[2695 2776 2744 ...  680  838  955]
[16, 54, 106]
62.9

Display cutted audio

Apply furier transform in order to see a "more readable plot"

Only matter the frequencies close to 0, so we take the first 300 elements from the furier array

In [127]:
#se recorta el audio a 3kHz por que más hz no tienen 



Delete noise from frequencies

In [129]:


np.argmax(out)

23

48
183
216


In [131]:
# for max in max_points:
#   print(max*Fs/fourier.size, 'Hz')

230.7923469898828 Hz
879.8958228989281 Hz
1038.5655614544726 Hz


Start the practice

In [108]:
import scipy.io.wavfile
import numpy as np 
import matplotlib.pyplot as plt 
from IPython.display import Audio 
from numpy.fft import fft, ifft 

Fs, audio = scipy.io.wavfile.read('audio2.wav')
arr_data = np.genfromtxt('../datasets/vocales.csv', delimiter=',')
arr_labels = np.genfromtxt('../datasets/vocales.csv', delimiter=',', dtype=str)

#elimino cabecera y output
arr_data = np.delete(arr_data, [0,-1], 0)
arr_data = np.delete(arr_data, [-1], 1)

In [114]:
def createVocalsDataset():
  for start, end in arr_data:
    cut = audio[int(start*Fs):int(end*Fs)]
    

createVocalsDataset()

7.819 8.027
13.311 13.416
17.654 17.757
16.437 16.548
17.533 17.603
13.198 13.272
22381.0 22736.0
29.798 29.917
7.919 8.018
21.145 21.295
12.718 12.862
20.144 20.337
6.305 6.419
28.502 28.648
51.107 51.185
62.957 63.071
32.001 32.109
34.709 34.816
35.256 35.357
36.251 36.355
6.742 6.847
27.091 27.13
11.279 11.454
17.951 18.073
23.192 23.319
30.445 30.605
44.077 44.201
15.174 15.285
21.454 21.538
27.626 27.721
8.803 8.921
14.739 14.833
47.187 47.336
31.411 31.513
31.665 31.828
32.337 32.421
33.75 33.866
34.303 34.419
36.057 36.159
38.05 38.158
40.871 41.037
44.58 44.682
47.711 47.824
51.47 51.582
54.042 54.122
59.699 59.809
63.422 63.56
72.102 72.154
73.587 73.711
